#!/bin/sh
#
# /etc/rc.d/tlp: start/stop slim
#

case $1 in
start)
	/usr/bin/tlp start
	;;
stop)
	killall /usr/bin/tlp
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file

