#!/bin/sh

/usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/Papirus-Adapta-Nokto
/usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/Papirus-Adapta
/usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/Papirus-Dark
/usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/Papirus-Light
/usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/ePapirus

# EOF
