#!/bin/sh
#
# This was originally my post-install for this port!
# consolekit2 and consolekit are not meant to co-exist, but
# the decision to swap out consolekit with consolekit2 is 
# only yours to make! Please review the consequences of this
# script!

alias="consolekit2: consolekit"

if [ -z "$(grep "$alias" /var/lib/pkg/prt-get.aliases)" ]; then
	echo "$alias" >> /var/lib/pkg/prt-get.aliases
fi
