#!/bin/sh
#
# /etc/rc.d/murmur: start/stop inet daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/bin/murmurd
PID=/var/run/murmurd.pid
OPTS="-ini /etc/murmur.ini"

case $1 in
start)
        $SSD --start -bm --pidfile $PID --exec $PROG -- $OPTS
         ;;
stop)
        $SSD --stop --remove-pidfile --retry 10  --pidfile $PID
        ;;
restart)
        $0 stop
        $0 start
        ;;
status)
        $SSD --status --exec $PROG --pidfile $PID
        case $? in
        0) echo "$PROG is running with pid $(pidof $PROG)" ;;
        1) echo "$PROG is not running but the pid file $PID exists" ;;
        3) echo "$PROG is not running" ;;
        4) echo "Unable to determine the program status" ;;
        esac
        ;;
*)
        echo "usage: $0 [start|stop|restart|status]"
        ;;
esac

# End of file

