#!/bin/sh

    getent group murmur > /dev/null || groupadd -g 122 murmur 1>/dev/null
    getent passwd murmur > /dev/null || useradd -u 122 -d /var/db/murmur -g murmur -s /bin/false murmur 1>/dev/null


